// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NerfBuff.Models;

namespace NerfBuff.Migrations
{
    [DbContext(typeof(masterContext))]
    [Migration("20181030122750_CreateBlogDB")]
    partial class CreateBlogDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NerfBuff.Models.Comments", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Author")
                        .HasMaxLength(10);

                    b.Property<string>("Content")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("PostId")
                        .HasColumnName("PostID");

                    b.Property<string>("Title")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("NerfBuff.Models.Events", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Author")
                        .HasMaxLength(10);

                    b.Property<string>("Location")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("NerfBuff.Models.Posts", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Author")
                        .HasMaxLength(30);

                    b.Property<string>("Content")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
